Deploying Functions as Eventable Services with RIFF [hint :RIFF Is For Functions]
=================================================================================
Mario Gray <mgray@pivotal.io>
:Author Initials: MVG
:toc:
:icons:
:numbered:
:website: https://github.com/projectriff/riff

With Functions, you can create software that instantly responds with demand.  
That is, traditional server-side application development -even simple web forms- 
must be provisioned for continual online operation. On the other hand, functions
let you guarantee availability of your application even when it is not online, 
hence when there is no demand.

RIFF is a FaaS platform that allows you to do exactly that. Deploy an application
function with elastic server usage.  Serving applications with functions enables
you to compose a   traditional workflow while effecting additional separation of
concerns.  Doing this enables your application to become fluid and more maintainable. 

Lets get started by setting up the Riff environment and then creating some functions.

.Bootstrapping Notice
**********************************************************************
All of the steps necessary to prepare the environment are outlined in 
the project Riff Github Repo.

RIFF Github repository https://github.com/projectriff/riff

Alternatively, read the <<X7, Bootstrapping>> section and take a look 
at the example script.
**********************************************************************

[[X7]]
Preparing the environment
~~~~~~~~~~~~~~~~~~~~~~~~~
Either use your existing Kubernetes environement, or alternatively 
check out these tools that provide a great alternative to installing
locally.  In this example, I am running a basic Minikube distrobution
with most recent hardware (16+ Gigs of Ram, 4 cores) based laptop or
Desktop configurations.

[[X8]]
Installation with Helm 
~~~~~~~~~~~~~~~~~~~~~~
Use Brew if you have macOS:  
[source,script,indent=0]
----
include::quick-helm.sh[lines=4]
----

Add the Helm chart for RIFF:
[source,script,indent=0]
----
include::helm-install.sh[lines=7..8]
----

Install RIFF:
[source,script,indent=0]
----
include::helm-install.sh[lines=12]
----

[[X9]]
Functional Service Developement
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
With Riff, you can implement functions in a few languages
at the current time of writing : [ Java, Python, Javascript, 
shell ]. Today, I am going to explore the aspect of running 
a small spring program as a function. The most basic function 
needs to be a class such as the following class:

.MinimumFunction.java
[source,java]
----
public class MyFunction extends java.util.function.Function<String,String> {
  public String apply(String arg) {
    return String.format("%s received", arg);
  }
}  
----

Riff Supports another functional type called the supplier.

.MinimumSupplier.java
[source,java]
----
public class MySupplier extends java.util.function.Supplier<Long> {
  public Long apply() { 
    return  System.currentTimeMillis();
  }
}
----
