Deploying Functions as Eventable Services with RIFF [hint :RIFF Is For Functions]
=================================================================================
Mario Gray <mgray@pivotal.io>
:Author Initials: MVG
:toc:
:icons:
:numbered:
:website: https://github.com/projectriff/riff

Motivation
~~~~~~~~~~
With Functions, you can create software that instantly responds with demand.  
That is, traditional server-side application development -even simple web forms- 
must be provisioned for continual online operation. On the other hand, functions
let you guarantee availability of your application even when it is not online, 
hence when there is no demand.

Deploying a server-less function will gain dramatic benefit since invoking a function
is just a topic away.  T
function with elastic server usage.  Serving applications with functions enables
you to compose a   traditional workflow while effecting additional separation of
concerns.  Doing this enables your application to become fluid and more maintainable. 

Lets get started by setting up the Riff environment and then creating some functions.

.Bootstrapping Notice
**********************************************************************
All of the steps necessary to manually prepare the environment are
outlined in the project Riff Github Repo.
https://github.com/projectriff/riff

I use Helm instead. Its nifty, and features ease of configuration
especially in a controlled environment such as desktop/laptop.
Refer to <<X7, Bootstrapping>> section and take a look at the
example script.  For more information on installing helm, refer to
the project's Installation guide.
https://docs.helm.sh/using_helm/#from-script
**********************************************************************

[[X7]]
Preparing the environment
~~~~~~~~~~~~~~~~~~~~~~~~~
Either use an existing Kubernetes environement, or alternatively 
check out these tools that provide a great alternative to installing
locally:

.I need links
----
Inserter k8s playground link
----

In this demo, I am assuming Minikube `0.24.1` with Helm `2.7.2`.

[[X8]]
Installation with Helm 
---
Use Brew if you have macOS:  
[source,script,indent=0]
----
brew install kubernetes-helm #<1>
apt-get install 
----

Add the Helm chart for RIFF:
[source,script,indent=0]
----
include::helm-install.sh[lines=7..8]
----

Install RIFF:
[source,script,indent=0]
----
include::helm-install.sh[lines=12]
----

**********************************************************************
NOTE: If your http-gateway fails to receive an External IP after some
time, then you may need to change service types.
[source,script,indent=0]
----
kubectl edit service demo-riff-http-gateway
----
Update the `type` field from `LoadBalancer` to `NodePort`, and save.
**********************************************************************

[[X9]]
Writing the Function.
~~~~~~~~~~~~~~~~~~~~~
Riff works by routing arguments via pub/sub channels Consider functions
as real time data processors that are activate upon message received
on a topic.
A function controller listens to requests via http and routes parameters
and return values to/from function executions.  The current addressability
for Riff topics exist through the http controller which by default accepts
String (java.lang.String) arguments and passes them into a designated topic
given by the scope of the HTTP request.  here are some examples of that 
communication in action:

This demonstration will use  get to the rest later :). To demonstrate a 
functional workflow I will implement the three most common or least hated
functional types - Function, Supplier, Consumer.

.DemoFunction.java
[source,java,indent=0]
----
include::demofn/src/main/java/com/codepub/demo/DemoFunction.java[lines=6..11]
----

Riff Supports another functional type called the supplier.

.DemoSupplier.java
[source,java]
----
include::demofn/src/main/java/com/codepub/demo/DemoSupplier.java[lines=7..12]
---- 
add elipsis

And the Consumer.  Among others [ insert others ] , try them all!

.DemoConsumer.java
[source,java]
----
include::demofn/src/main/java/com/codepub/demo/DemoConsumer.java[lines=10..15]
----

Executing the function
~~~~~~~~~~~~~~~~~~~~~~
In order to get all this working, we will need to create
the Riff service images and have them deployed.
we can create our own Dockerfile, service description
and container images manually.  However since 0.0.3 we get
the ability to do this with the `riff` comand automatically!

This command lets you create your function by naming it,
naming the input and output topics, and provide a functional
class method to execute upon trigger.

.RiffSetup-Supplier.sh
[source,script]
----
include::demofn/inst.sh[lines=34..37]
----

