apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: demoinput
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: demooutput
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: demofn
spec:
  protocol: pipes
  input: demoinput
  output: demooutput
  container:
    image: projectriff/spring-fn-basics:0.0.1
