apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: cin
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: cout
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: springfn
spec:
  protocol: pipes
  input: cin
  output: cout
  container:
    image: projectriff/springfn:0.0.2
