apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: springin
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: springout
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: springfn
spec:
  protocol: pipes
  input: springin
  output: springout
  container:
    image: mariogray/springfn:0.0.3
